// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module load_input20 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        in1_TDATA,
        in1_TVALID,
        in1_TREADY,
        in1_TKEEP,
        in1_TSTRB,
        in1_TUSER,
        in1_TLAST,
        in1_TID,
        in1_TDEST,
        size_dout,
        size_empty_n,
        size_read,
        size_out_din,
        size_out_full_n,
        size_out_write,
        in1_stream_V_din,
        in1_stream_V_full_n,
        in1_stream_V_write
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_pp0_stage0 = 3'd2;
parameter    ap_ST_fsm_state4 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [31:0] in1_TDATA;
input   in1_TVALID;
output   in1_TREADY;
input  [3:0] in1_TKEEP;
input  [3:0] in1_TSTRB;
input  [3:0] in1_TUSER;
input  [0:0] in1_TLAST;
input  [4:0] in1_TID;
input  [4:0] in1_TDEST;
input  [31:0] size_dout;
input   size_empty_n;
output   size_read;
output  [31:0] size_out_din;
input   size_out_full_n;
output   size_out_write;
output  [31:0] in1_stream_V_din;
input   in1_stream_V_full_n;
output   in1_stream_V_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg in1_TREADY;
reg size_read;
reg size_out_write;
reg in1_stream_V_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    in1_TDATA_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
wire    ap_block_pp0_stage0;
wire   [0:0] icmp_ln10_fu_154_p2;
reg    size_blk_n;
reg    size_out_blk_n;
reg    in1_stream_V_blk_n;
reg    ap_enable_reg_pp0_iter1;
reg   [0:0] icmp_ln10_reg_178;
reg   [30:0] i_0_i_i_reg_139;
reg   [31:0] size_read_reg_173;
reg    ap_block_state1;
reg    ap_block_state2_pp0_stage0_iter0;
reg    ap_block_state3_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_11001;
wire   [30:0] add_ln10_fu_159_p2;
reg   [31:0] in_data_V_tmp_reg_187;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state2;
reg    ap_block_pp0_stage0_01001;
wire   [31:0] i_0_i_i_cast_fu_150_p1;
wire    ap_CS_fsm_state4;
reg   [2:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire    regslice_both_in_data_V_U_apdone_blk;
wire   [31:0] in1_TDATA_int;
wire    in1_TVALID_int;
reg    in1_TREADY_int;
wire    regslice_both_in_data_V_U_ack_in;
wire    regslice_both_in_keep_V_U_apdone_blk;
wire   [3:0] in1_TKEEP_int;
wire    regslice_both_in_keep_V_U_vld_out;
wire    regslice_both_in_keep_V_U_ack_in;
wire    regslice_both_in_strb_V_U_apdone_blk;
wire   [3:0] in1_TSTRB_int;
wire    regslice_both_in_strb_V_U_vld_out;
wire    regslice_both_in_strb_V_U_ack_in;
wire    regslice_both_in_user_V_U_apdone_blk;
wire   [3:0] in1_TUSER_int;
wire    regslice_both_in_user_V_U_vld_out;
wire    regslice_both_in_user_V_U_ack_in;
wire    regslice_both_in_last_V_U_apdone_blk;
wire   [0:0] in1_TLAST_int;
wire    regslice_both_in_last_V_U_vld_out;
wire    regslice_both_in_last_V_U_ack_in;
wire    regslice_both_in_id_V_U_apdone_blk;
wire   [4:0] in1_TID_int;
wire    regslice_both_in_id_V_U_vld_out;
wire    regslice_both_in_id_V_U_ack_in;
wire    regslice_both_in_dest_V_U_apdone_blk;
wire   [4:0] in1_TDEST_int;
wire    regslice_both_in_dest_V_U_vld_out;
wire    regslice_both_in_dest_V_U_ack_in;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
end

regslice_both #(
    .DataWidth( 32 ))
regslice_both_in_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(in1_TDATA),
    .vld_in(in1_TVALID),
    .ack_in(regslice_both_in_data_V_U_ack_in),
    .data_out(in1_TDATA_int),
    .vld_out(in1_TVALID_int),
    .ack_out(in1_TREADY_int),
    .apdone_blk(regslice_both_in_data_V_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 4 ))
regslice_both_in_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(in1_TKEEP),
    .vld_in(in1_TVALID),
    .ack_in(regslice_both_in_keep_V_U_ack_in),
    .data_out(in1_TKEEP_int),
    .vld_out(regslice_both_in_keep_V_U_vld_out),
    .ack_out(in1_TREADY_int),
    .apdone_blk(regslice_both_in_keep_V_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 4 ))
regslice_both_in_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(in1_TSTRB),
    .vld_in(in1_TVALID),
    .ack_in(regslice_both_in_strb_V_U_ack_in),
    .data_out(in1_TSTRB_int),
    .vld_out(regslice_both_in_strb_V_U_vld_out),
    .ack_out(in1_TREADY_int),
    .apdone_blk(regslice_both_in_strb_V_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 4 ))
regslice_both_in_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(in1_TUSER),
    .vld_in(in1_TVALID),
    .ack_in(regslice_both_in_user_V_U_ack_in),
    .data_out(in1_TUSER_int),
    .vld_out(regslice_both_in_user_V_U_vld_out),
    .ack_out(in1_TREADY_int),
    .apdone_blk(regslice_both_in_user_V_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 1 ))
regslice_both_in_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(in1_TLAST),
    .vld_in(in1_TVALID),
    .ack_in(regslice_both_in_last_V_U_ack_in),
    .data_out(in1_TLAST_int),
    .vld_out(regslice_both_in_last_V_U_vld_out),
    .ack_out(in1_TREADY_int),
    .apdone_blk(regslice_both_in_last_V_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 5 ))
regslice_both_in_id_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(in1_TID),
    .vld_in(in1_TVALID),
    .ack_in(regslice_both_in_id_V_U_ack_in),
    .data_out(in1_TID_int),
    .vld_out(regslice_both_in_id_V_U_vld_out),
    .ack_out(in1_TREADY_int),
    .apdone_blk(regslice_both_in_id_V_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 5 ))
regslice_both_in_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(in1_TDEST),
    .vld_in(in1_TVALID),
    .ack_in(regslice_both_in_dest_V_U_ack_in),
    .data_out(in1_TDEST_int),
    .vld_out(regslice_both_in_dest_V_U_vld_out),
    .ack_out(in1_TREADY_int),
    .apdone_blk(regslice_both_in_dest_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state4)) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_condition_pp0_exit_iter0_state2) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if ((~((ap_start == 1'b0) | (size_out_full_n == 1'b0) | (size_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_condition_pp0_exit_iter0_state2) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state2);
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if ((~((ap_start == 1'b0) | (size_out_full_n == 1'b0) | (size_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln10_fu_154_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        i_0_i_i_reg_139 <= add_ln10_fu_159_p2;
    end else if ((~((ap_start == 1'b0) | (size_out_full_n == 1'b0) | (size_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        i_0_i_i_reg_139 <= 31'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln10_reg_178 <= icmp_ln10_fu_154_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln10_fu_154_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_data_V_tmp_reg_187 <= in1_TDATA_int;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | (size_out_full_n == 1'b0) | (size_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        size_read_reg_173 <= size_dout;
    end
end

always @ (*) begin
    if ((icmp_ln10_fu_154_p2 == 1'd0)) begin
        ap_condition_pp0_exit_iter0_state2 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state2 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln10_fu_154_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in1_TDATA_blk_n = in1_TVALID_int;
    end else begin
        in1_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((in1_TVALID == 1'b1) & (regslice_both_in_data_V_U_ack_in == 1'b1))) begin
        in1_TREADY = 1'b1;
    end else begin
        in1_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln10_fu_154_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in1_TREADY_int = 1'b1;
    end else begin
        in1_TREADY_int = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln10_reg_178 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in1_stream_V_blk_n = in1_stream_V_full_n;
    end else begin
        in1_stream_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln10_reg_178 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in1_stream_V_write = 1'b1;
    end else begin
        in1_stream_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        size_blk_n = size_empty_n;
    end else begin
        size_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        size_out_blk_n = size_out_full_n;
    end else begin
        size_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (size_out_full_n == 1'b0) | (size_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        size_out_write = 1'b1;
    end else begin
        size_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (size_out_full_n == 1'b0) | (size_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        size_read = 1'b1;
    end else begin
        size_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_start == 1'b0) | (size_out_full_n == 1'b0) | (size_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if (~((icmp_ln10_fu_154_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((icmp_ln10_fu_154_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln10_fu_159_p2 = (i_0_i_i_reg_139 + 31'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd2];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((icmp_ln10_reg_178 == 1'd1) & (in1_stream_V_full_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((icmp_ln10_fu_154_p2 == 1'd1) & (in1_TVALID_int == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((icmp_ln10_reg_178 == 1'd1) & (in1_stream_V_full_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((icmp_ln10_fu_154_p2 == 1'd1) & (in1_TVALID_int == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((icmp_ln10_reg_178 == 1'd1) & (in1_stream_V_full_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((icmp_ln10_fu_154_p2 == 1'd1) & (in1_TVALID_int == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)));
end

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (size_out_full_n == 1'b0) | (size_empty_n == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter0 = ((icmp_ln10_fu_154_p2 == 1'd1) & (in1_TVALID_int == 1'b0));
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter1 = ((icmp_ln10_reg_178 == 1'd1) & (in1_stream_V_full_n == 1'b0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign i_0_i_i_cast_fu_150_p1 = i_0_i_i_reg_139;

assign icmp_ln10_fu_154_p2 = (($signed(i_0_i_i_cast_fu_150_p1) < $signed(size_read_reg_173)) ? 1'b1 : 1'b0);

assign in1_stream_V_din = in_data_V_tmp_reg_187;

assign size_out_din = size_dout;

endmodule //load_input20
